name: Laravel Test with Docker Compose

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy .env file
      run: cp src/.env.example src/.env
        
    - name: docker compose
      run: |
        docker compose up -d
        docker-compose exec -T laravel bash -c "composer install"
        # docker-compose exec -T laravel bash -c "cp .env.example .env"
        docker-compose exec -T laravel bash -c "php artisan key:generate"
        docker-compose exec -T laravel bash -c "php artisan config:cache"
        docker-compose exec -T laravel bash -c "sleep 200"

    - name: migrate
      run: |
        docker-compose exec -T laravel bash -c "php artisan migrate"

    - name: Exec Phpunit
      run: |
        docker-compose exec -T laravel bash -c "php vendor/bin/phpunit"

    - name: view laravel.log
      run: |
        docker-compose exec -T laravel bash -c "cat storage/logs/laravel.log"
      if: ${{ failure() }}
