name: Laravel Test with Docker Compose

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy .env file
      run: cp src/.env.example src/.env
        
    - name: dokcer compose
      run: |
        docker compose up -d --build
        
    - name: composer install
      run: |
        docker exec -T laravel bash -c "composer install"
        
    - name: migrate
      run: |
        docker exec -T laravel bash -c "php artisan migrate"

    - name: Exec Phpunit
      run: |
        docker exec -T laravel bash -c "php vendor/bin/phpunit"

    - name: view laravel.log
      run: |
        docker exec -T laravel bash -c "cat storage/logs/laravel.log"
      if: ${{ failure() }}
