name: Laravel Test with Docker Compose

on:
  pull_request:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Install Dependencies
      run: docker exec laravel composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: docker exec laravel cp .env.example .env

    - name: Generate Key
      run: docker exec laravel php artisan key:generate

    - name: Run Migrations
      run: docker exec laravel php artisan migrate

    - name: Run Tests
      run: docker exec laravel vendor/bin/phpunit
