name: Laravel Test with Docker Compose

on:
  pull_request:
    branches:
      - develop

jobs:
  laravel-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: dokcer-compose Laravel Init
      run: |
        docker-compose up -d
        
    - name: composer install
      run: |
        docker-compose exec -T laravel bash -c "composer install"
        
    - name: migrate
        docker-compose exec -T laravel bash -c "php artisan migrate"

    - name: Exec Phpunit
      run: |
        docker-compose exec -T laravel bash -c "vendor/bin/phpunit"
