name: Laravel Test on Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: kickoffreminder
          MYSQL_USER: test
          MYSQL_PASSWORD: test123
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql
        tools: composer, phpunit

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # - name: Run Migrations
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_HOST: 127.0.0.1
    #     DB_PORT: 3306
    #     DB_DATABASE: kickoffreminder
    #     DB_USERNAME: test
    #     DB_PASSWORD: test123
    #   run: php artisan migrate

    # - name: Run Tests
    #   run: vendor/bin/phpunit
