<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StandingSeeder extends Seeder
{
    public function run()
    {

        DB::table('standings')->insert([
            [
                'id' => 1,
                'position' => 1,
                'played_games' => 1,
                'won' => 25,
                'draw' => 10,
                'lost' => 3,
                'goals_for' => 87,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 85,
                'team_id' => 65,
                'season_id' => 1564,
            ],
            [
                'id' => 555,
                'position' => 4,
                'played_games' => 31,
                'won' => 15,
                'draw' => 10,
                'lost' => 3,
                'goals_for' => 87,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 85,
                'team_id' => 66,
                'season_id' => 1564,
            ],
            [
                'id' => 51,
                'position' => 5,
                'played_games' => 1,
                'won' => 13,
                'draw' => 9,
                'lost' => 23,
                'goals_for' => 87,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 44,
                'team_id' => 397,
                'season_id' => 1564,
            ],
            [
                'id' => 34,
                'position' => 6,
                'played_games' => 32,
                'won' => 5,
                'draw' => 10,
                'lost' => 23,
                'goals_for' => 37,
                'goals_against' => 53,
                'goal_difference' => -22,
                'points' => 35,
                'team_id' => 64,
                'season_id' => 1564,
            ],
            [
                'id' => 1019,
                'position' => 18,
                'played_games' => 38,
                'won' => 25,
                'draw' => 10,
                'lost' => 3,
                'goals_for' => 66,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 85,
                'team_id' => 57,
                'season_id' => 733,
            ],
            [
                'id' => 1011,
                'position' => 12,
                'played_games' => 11,
                'won' => 25,
                'draw' => 10,
                'lost' => 3,
                'goals_for' => 80,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 85,
                'team_id' => 57,
                'season_id' => 1490,
            ],
            [
                'id' => 10,
                'position' => 2,
                'played_games' => 31,
                'won' => 25,
                'draw' => 16,
                'lost' => 3,
                'goals_for' => 67,
                'goals_against' => 32,
                'goal_difference' => 53,
                'points' => 55,
                'team_id' => 57,
                'season_id' => 1564,
            ],
            [
                'id' => 5,
                'position' => 3,
                'played_games' => 32,
                'won' => 15,
                'draw' => 17,
                'lost' => 8,
                'goals_for' => 44,
                'goals_against' => 43,
                'goal_difference' => 33,
                'points' => 85,
                'team_id' => 61,
                'season_id' => 1564,
            ],
            [
                'id' => 4,
                'position' => 1,
                'played_games' => 1,
                'won' => 25,
                'draw' => 10,
                'lost' => 3,
                'goals_for' => 87,
                'goals_against' => 33,
                'goal_difference' => 63,
                'points' => 85,
                'team_id' => 5,
                'season_id' => 742,
            ],


        ]);
    }
}
