<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    public function run()
    {
        DB::table('teams')->insert([
            // プレミアリーグ
            [
                'id' => 57,
                'name' => 'アーセナル',
                'short_name' => null,
                'crest' => '57.png',
                'venue' => 'エミレーツスタジアム',
                'website_url' => 'https://www.arsenal.com/',
                'twitter_url' => 'https://twitter.com/arsenal_japan/',
                'youtube_url' => 'https://www.youtube.com/arsenal/',
                'instagram_url' => 'http://instagram.com/arsenal/',
            ],
            [
                'id' => 58,
                'name' => 'アストン・ビラ',
                'short_name' => null,
                'crest' => '58.png',
                'venue' => 'ヴィラ・パーク',
                'website_url' => 'http://www.avfc.co.uk',
                'twitter_url' => 'https://twitter.com/avfcofficial',
                'youtube_url' => 'https://www.youtube.com/avfcofficial',
                'instagram_url' => 'https://www.instagram.com/avfcofficial/',
            ],
            [
                'id' => 61,
                'name' => 'チェルシー',
                'short_name' => null,
                'crest' => '61.png',
                'venue' => 'スタンフォード・ブリッジ',
                'website_url' => 'https://www.chelseafc.com/ ',
                'twitter_url' => 'https://twitter.com/ChelseaFC',
                'youtube_url' => 'https://www.youtube.com/chelseafc',
                'instagram_url' => 'https://www.instagram.com/chelseafc/',
            ],
            [
                'id' => 62,
                'name' => 'エヴァートン',
                'short_name' => null,
                'crest' => '62.png',
                'venue' => 'グディソン・パーク',
                'website_url' => 'https://www.evertonfc.com/',
                'twitter_url' => 'https://twitter.com/everton/',
                'youtube_url' => 'https://www.youtube.com/everton',
                'instagram_url' => 'https://www.instagram.com/everton/',
            ],
            [
                'id' => 63,
                'name' => 'フラム',
                'short_name' => null,
                'crest' => '63.png',
                'venue' => 'クレイヴン・コテージ',
                'website_url' => 'http://www.fulhamfc.com',
                'twitter_url' => 'https://twitter.com/FulhamFC',
                'youtube_url' => 'https://www.youtube.com/FulhamFC1987Ltd',
                'instagram_url' => 'https://www.instagram.com/fulhamfc/',
            ],
            [
                'id' => 64,
                'name' => 'リヴァプール',
                'short_name' => null,
                'crest' => '64.png',
                'venue' => 'アンフィールド',
                'website_url' => 'https://www.liverpoolfc.com/',
                'twitter_url' => 'https://twitter.com/lfc/',
                'youtube_url' => 'https://www.youtube.com/liverpoolfc',
                'instagram_url' => 'https://www.instagram.com/liverpoolfc/',
            ],
            [
                'id' => 65,
                'name' => 'マンチェスター・シティ',
                'short_name' => 'マンチェスターC',
                'crest' => '65.png',
                'venue' => 'スタンフォード・ブリッジ',
                'website_url' => 'https://www.mancity.com',
                'twitter_url' => 'https://twitter.com/ManCity',
                'youtube_url' => 'https://www.youtube.com/mcfcofficial',
                'instagram_url' => 'https://www.instagram.com/mancity/',
            ],
            [
                'id' => 66,
                'name' => 'マンチェスター・ユナイテッド',
                'short_name' => 'マンチェスターU',
                'crest' => '66.png',
                'venue' => 'オールド・トラッフォード',
                'website_url' => 'https://www.manutd.com/en',
                'twitter_url' => 'https://twitter.com/ManUtd',
                'youtube_url' => 'https://www.youtube.com/manutd',
                'instagram_url' => 'https://www.instagram.com/manchesterunited/',
            ],
            [
                'id' => 397,
                'name' => 'ブライトン・アンド・ホーヴ・アルビオン',
                'short_name' => 'ブライトン',
                'crest' => '397.png',
                'venue' => 'ファルマー・スタジアム',
                'website_url' => 'https://www.brightonandhovealbion.com/',
                'twitter_url' => 'https://twitter.com/OfficialBHAFC/',
                'youtube_url' => 'https://www.youtube.com/officialbhafc',
                'instagram_url' => 'https://www.instagram.com/officialbhafc/',
            ],
            [
                'id' => 67,
                'name' => 'ニューカッスル・ユナイテッド',
                'short_name' => 'ニューカッスル',
                'crest' => '67.png',
                'venue' => 'セント・ジェームズ・パーク',
                'website_url' => 'https://www.nufc.co.uk/',
                'twitter_url' => 'https://twitter.com/NUFC/',
                'youtube_url' => 'https://www.youtube.com/NUFCOfficial1892',
                'instagram_url' => 'https://www.instagram.com/nufc/',
            ],
            [
                'id' => 73,
                'name' => 'トッテナム・ホットスパー',
                'short_name' => 'トッテナム',
                'crest' => '73.png',
                'venue' => 'トッテナム・ホットスパー・スタジアム',
                'website_url' => 'https://www.tottenhamhotspur.com/',
                'twitter_url' => 'https://twitter.com/SpursOfficial/',
                'youtube_url' => 'https://www.youtube.com/spursofficial',
                'instagram_url' => 'https://www.instagram.com/spursofficial',
            ],
            [
                'id' => 76,
                'name' => 'ウルヴァーハンプトン・ワンダラーズ',
                'short_name' => 'ウルブス',
                'crest' => '76.png',
                'venue' => 'モリニュー・スタジアム',
                'website_url' => 'https://www.wolves.co.uk/',
                'twitter_url' => 'https://twitter.com/Wolves',
                'youtube_url' => 'https://www.youtube.com/OfficialWolvesVideo',
                'instagram_url' => 'https://www.instagram.com/wolves/',
            ],
            [
                'id' => 338,
                'name' => 'レスター・シティ',
                'short_name' => 'レスター',
                'crest' => '338.png',
                'venue' => null,
                'website_url' => 'http://www.lcfc.com',
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 340,
                'name' => 'サウサンプトン',
                'short_name' => null,
                'crest' => '340.png',
                'venue' => null,
                'website_url' => 'https://www.southamptonfc.com/',
                'twitter_url' => 'https://twitter.com/southamptonfc',
                'youtube_url' => 'https://www.youtube.com/theofficialsaints',
                'instagram_url' => 'https://www.instagram.com/southamptonfc/',
            ],
            [
                'id' => 341,
                'name' => 'リーズ・ユナイテッド',
                'short_name' => 'リーズU',
                'crest' => '341.png',
                'venue' => null,
                'website_url' => 'http://www.leedsunited.com',
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 351,
                'name' => 'ノッティンガム・フォレスト',
                'short_name' => 'ノッティンガム',
                'crest' => '351.png',
                'venue' => 'シティ・グラウンド',
                'website_url' => 'https://www.nottinghamforest.co.uk/',
                'twitter_url' => 'https://twitter.com/NFFC',
                'youtube_url' => 'https://www.youtube.com/NFFCTube',
                'instagram_url' => 'https://www.instagram.com/officialnffc/',
            ],
            [
                'id' => 354,
                'name' => 'クリスタル・パレス',
                'short_name' => 'クリスタルパレス',
                'crest' => '354.png',
                'venue' => 'セルハースト・パーク',
                'website_url' => 'https://www.cpfc.co.uk/',
                'twitter_url' => 'https://twitter.com/CPFC/',
                'youtube_url' => 'https://www.youtube.com/OfficialCPFC',
                'instagram_url' => 'https://www.instagram.com/cpfc/',
            ],
            [
                'id' => 402,
                'name' => 'ブレントフォード',
                'short_name' => null,
                'crest' => '402.png',
                'venue' => 'ブレントフォード・コミュニティ・スタジアム',
                'website_url' => 'https://www.brentfordfc.com',
                'twitter_url' => 'https://twitter.com/BrentfordFC',
                'youtube_url' => 'https://www.youtube.com/BrentfordFC',
                'instagram_url' => 'https://www.instagram.com/brentfordfc/',
            ],
            [
                'id' => 563,
                'name' => 'ウェストハム・ユナイテッド',
                'short_name' => 'ウェストハム',
                'crest' => '563.png',
                'venue' => 'ロンドン・スタジアム',
                'website_url' => 'https://www.whufc.com/',
                'twitter_url' => 'https://twitter.com/WestHam',
                'youtube_url' => 'https://www.youtube.com/westhamunited',
                'instagram_url' => 'https://www.instagram.com/westham/',
            ],
            [
                'id' => 1044,
                'name' => 'ボーンマス',
                'short_name' => 'ボーンマス',
                'crest' => '1044.png',
                'venue' => 'バイタリティー・スタジアム',
                'website_url' => 'https://www.afcb.co.uk/',
                'twitter_url' => 'https://twitter.com/afcbournemouth/',
                'youtube_url' => 'https://www.youtube.com/afcbournemouth/',
                'instagram_url' => 'https://www.instagram.com/afcb/',
            ],
            [
                'id' => 356,
                'name' => 'シェフィールド・ユナイテッド',
                'short_name' => 'シェフィールドU',
                'crest' => '356.png',
                'venue' => 'ブラモール・レーン',
                'website_url' => 'https://www.sufc.co.uk/',
                'twitter_url' => 'https://twitter.com/SheffieldUnited/',
                'youtube_url' => 'https://www.youtube.com/SheffieldUTube',
                'instagram_url' => 'https://www.instagram.com/sheffieldunited/',
            ],
            [
                'id' => 389,
                'name' => 'ルートン・タウン',
                'short_name' => 'ルートンタウン',
                'crest' => '389.png',
                'venue' => 'ケニルワース・ロード',
                'website_url' => 'https://www.lutontown.co.uk/',
                'twitter_url' => 'https://twitter.com/lutontown',
                'youtube_url' => 'https://www.youtube.com/OfficialLutonTown',
                'instagram_url' => 'https://www.instagram.com/lutontown/',
            ],
            [
                'id' => 328,
                'name' => 'バーンリー',
                'short_name' => null,
                'crest' => '328.png',
                'venue' => 'ターフ・ムーア',
                'website_url' => 'https://www.burnleyfootballclub.com/',
                'twitter_url' => 'https://twitter.com/BurnleyOfficial/',
                'youtube_url' => 'https://www.youtube.com/officialburnleyfc/',
                'instagram_url' => 'https://www.instagram.com/burnleyofficial/',
            ],

            // リーガエスパニョーラ
            [
                'id' => 81,
                'name' => 'FCバルセロナ',
                'short_name' => 'バルセロナ',
                'crest' => '81.png',
                'venue' => 'カンプ・ノウ',
                'website_url' => 'http://www.fcbarcelona.com',
                'twitter_url' => 'https://twitter.com/FCBarcelona',
                'youtube_url' => 'https://www.youtube.com/FCBarcelona',
                'instagram_url' => 'https://www.instagram.com/fcbarcelona/',
            ],
            [
                'id' => 86,
                'name' => 'レアル・マドリード',
                'short_name' => null,
                'crest' => '86.png',
                'venue' => 'エスタディオ・サンティアゴ・ベルナベウ',
                'website_url' => 'http://www.realmadrid.com',
                'twitter_url' => 'https://twitter.com/realmadrid',
                'youtube_url' => 'https://www.youtube.com/realmadrid',
                'instagram_url' => 'https://www.instagram.com/realmadrid/',
            ],
            [
                'id' => 78,
                'name' => 'アトレティコ・マドリード',
                'short_name' => 'アトレティコ',
                'short_name' => null,
                'crest' => '78.png',
                'venue' => 'ワンダ・メトロポリターノ',
                'website_url' => 'http://www.clubatleticodemadrid.com',
                'twitter_url' => 'https://twitter.com/Atleti',
                'youtube_url' => 'https://www.youtube.com/atleticodemadrid',
                'instagram_url' => 'https://www.instagram.com/atleticodemadrid/',
            ],
            [
                'id' => 92,
                'name' => 'レアル・ソシエダ',
                'short_name' => 'ソシエダ',
                'crest' => '92.png',
                'venue' => 'エスタディオ・アノエタ',
                'website_url' => 'http://www.realsociedad.com',
                'twitter_url' => 'https://twitter.com/RealSociedad',
                'youtube_url' => 'https://www.youtube.com/realsociedadtv',
                'instagram_url' => 'https://www.instagram.com/realsociedad/',
            ],
            [
                'id' => 90,
                'name' => 'レアル・ベティス',
                'short_name' => 'ベティス',
                'crest' => '90.png',
                'venue' => 'エスタディオ・ベニート・ヴィジャマリン',
                'website_url' => 'https://en.realbetisbalompie.es/',
                'twitter_url' => 'https://twitter.com/RealBetis',
                'youtube_url' => 'https://www.youtube.com/RealBetis',
                'instagram_url' => 'https://www.instagram.com/realbetisbalompie/',
            ],
            [
                'id' => 94,
                'name' => 'ビジャレアル',
                'short_name' => null,
                'crest' => '94.png',
                'venue' => 'エスタディオ・デ・ラ・セラミカ',
                'website_url' => 'http://www.villarrealcf.es',
                'twitter_url' => 'https://twitter.com/VillarrealCF',
                'youtube_url' => 'https://www.youtube.com/villarrealcf',
                'instagram_url' => 'https://www.instagram.com/villarrealcf/',
            ],
            [
                'id' => 77,
                'name' => 'アスレティック・ビルバオ',
                'short_name' => 'ビルバオ',
                'crest' => '77.png',
                'venue' => 'サン・マメス',
                'website_url' => 'https://www.athletic-club.eus/en',
                'twitter_url' => 'https://twitter.com/AthleticClub',
                'youtube_url' => 'https://www.youtube.com/TVAthleticClub',
                'instagram_url' => 'https://www.instagram.com/athleticclub/',
            ],
            [
                'id' => 87,
                'name' => 'ラージョ・バジェカーノ',
                'short_name' => 'ラージョ',
                'crest' => '87.png',
                'venue' => 'カンポ・デ・フトボル・デ・バジェカス',
                'website_url' => 'https://www.rayovallecano.es/',
                'twitter_url' => 'https://twitter.com/RayoVallecano',
                'youtube_url' => 'https://www.youtube.com/rayovallecanotv',
                'instagram_url' => 'https://www.instagram.com/rayovallecano/',
            ],
            [
                'id' => 79,
                'name' => 'オサスナ',
                'short_name' => null,
                'crest' => '79.png',
                'venue' => 'エスタディオ・エル・サダー',
                'website_url' => 'https://www.osasuna.es/',
                'twitter_url' => 'https://twitter.com/Osasuna',
                'youtube_url' => 'https://www.youtube.com/@caosasunatv',
                'instagram_url' => 'https://www.instagram.com/caosasuna/',
            ],
            [
                'id' => 558,
                'name' => 'セルタ・デ・ビーゴ',
                'short_name' => 'セルタ',
                'crest' => '558.png',
                'venue' => 'エスタディオ・デ・バライードス',
                'website_url' => 'https://rccelta.es/en',
                'twitter_url' => 'https://twitter.com/rccelta',
                'youtube_url' => 'https://www.youtube.com/RealClubCeltadeVigo',
                'instagram_url' => null,
            ],
            [
                'id' => 298,
                'name' => 'ジローナ',
                'short_name' => null,
                'crest' => '298.png',
                'venue' => 'エスタディ・モンティリビ',
                'website_url' => 'http://www.gironafc.cat',
                'twitter_url' => 'https://twitter.com/gironafc',
                'youtube_url' => 'https://www.youtube.com/gironafcvideos1213',
                'instagram_url' => 'https://www.instagram.com/gironafc/',
            ],
            [
                'id' => 89,
                'name' => 'マジョルカ',
                'short_name' => null,
                'crest' => '89.png',
                'venue' => 'エスタディ・デ・ソン・モイシュ',
                'website_url' => 'https://www.rcdmallorca.es/en',
                'twitter_url' => 'https://twitter.com/RCD_Mallorca',
                'youtube_url' => 'https://www.youtube.com/OficialRCDMallorca',
                'instagram_url' => 'https://www.instagram.com/rcdmallorcaoficial/',
            ],
            [
                'id' => 559,
                'name' => 'セビージャ',
                'short_name' => null,
                'crest' => '559.png',
                'venue' => 'エスタディオ・ラモン・サンチェス・ピスファン',
                'website_url' => 'https://sevillafc.es/en',
                'twitter_url' => 'https://twitter.com/SevillaFC',
                'youtube_url' => 'https://www.youtube.com/sevillafc',
                'instagram_url' => 'https://www.instagram.com/sevillafc/',
            ],
            [
                'id' => 82,
                'name' => 'ヘタフェ',
                'short_name' => null,
                'crest' => '82.png',
                'venue' => 'エスタディオ・コリセウム・アルフォンソ・ペレス',
                'website_url' => 'https://www.getafecf.com/',
                'twitter_url' => 'https://twitter.com/GetafeCF',
                'youtube_url' => 'https://www.youtube.com/getafecdefsad',
                'instagram_url' => 'https://www.instagram.com/getafecf/',
            ],
            [
                'id' => 264,
                'name' => 'カディス',
                'short_name' => null,
                'crest' => '264.png',
                'venue' => 'エスタディオ・ラモン・デ・カッランツァ',
                'website_url' => 'https://www.cadizcf.com/',
                'twitter_url' => 'https://twitter.com/cadiz_cf',
                'youtube_url' => 'https://www.youtube.com/cadizcf',
                'instagram_url' => 'https://www.instagram.com/cadizclubdefutbol/',
            ],
            [
                'id' => 250,
                'name' => 'バジャドリード',
                'short_name' => null,
                'crest' => '250.png',
                'venue' => 'エスタディオ・ホセ・ソリージャ',
                'website_url' => 'http://www.realvalladolid.es',
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 95,
                'name' => 'バレンシア',
                'short_name' => null,
                'crest' => '95.png',
                'venue' => 'エスタディオ・デ・メスタージ',
                'website_url' => 'http://www.valenciacf.com',
                'twitter_url' => 'https://twitter.com/valenciacf',
                'youtube_url' => 'https://www.youtube.com/valenciacf',
                'instagram_url' => 'https://www.instagram.com/valenciacf/',
            ],
            [
                'id' => 80,
                'name' => 'エスパニョール',
                'short_name' => null,
                'crest' => '80.png',
                'venue' => 'RCDEスタジアム',
                'website_url' => 'https://www.rcdespanyol.com/en/',
                'twitter_url' => 'https://twitter.com/rcdespanyol',
                'youtube_url' => 'https://www.youtube.com/espanyoltv',
                'instagram_url' => 'https://www.instagram.com/RCDEspanyol/',
            ],
            [
                'id' => 267,
                'name' => 'アルメリア',
                'short_name' => null,
                'crest' => '267.png',
                'venue' => null,
                'website_url' => 'http://www.udalmeriasad.com',
                'twitter_url' => 'https://twitter.com/U_D_Almeria',
                'youtube_url' => 'https://www.youtube.com/udalmeria6110',
                'instagram_url' => 'https://www.instagram.com/udalmeria/',
            ],
            [
                'id' => 285,
                'name' => 'エルチェ',
                'short_name' => null,
                'crest' => '285.png',
                'venue' => 'エスタディオ・マヌエル・マルティネス・ヴァレーロ',
                'website_url' => 'http://www.elchecf.es',
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 263,
                'name' => 'デポルティーボ・アラベス',
                'short_name' => 'アラベス',
                'crest' => '263.png',
                'venue' => 'エスタディオ・デ・メンディソロツァ',
                'website_url' => 'https://www.deportivoalaves.com/es/',
                'twitter_url' => 'https://twitter.com/alaves',
                'youtube_url' => 'http://www.youtube.com/deportivoalaves1921',
                'instagram_url' => 'https://instagram.com/deportivoalaves/',
            ],
            [
                'id' => 275,
                'name' => 'ラス・パルマス',
                'short_name' => null,
                'crest' => '275.png',
                'venue' => 'エスタディオ・グラン・カナリア',
                'website_url' => 'https://www.udlaspalmas.es/en',
                'twitter_url' => 'http://www.twitter.com/UDLP_english',
                'youtube_url' => null,
                'instagram_url' => 'http://instagram.com/udlaspalmasoficial',
            ],
            [
                'id' => 83,
                'name' => 'グラナダ',
                'short_name' => null,
                'crest' => null,
                'venue' => 'ヌエボ・ロス・カルメネス',
                'website_url' => 'https://www.granadacf.es/',
                'twitter_url' => 'https://twitter.com/GranadaCF',
                'youtube_url' => 'https://www.youtube.com/c/GranadaCFtv',
                'instagram_url' => 'https://instagram.com/granadacf',
            ],
            // ブンデスリーガ
            [
                'id' => 5,
                'name' => 'バイエルン・ミュンヘン',
                'short_name' => 'バイエルン',
                'crest' => '5.png',
                'venue' => 'アリアンツ アレーナ',
                'website_url' => 'https://fcbayern.com/en',
                'twitter_url' => 'https://twitter.com/FCBayern',
                'youtube_url' => 'https://www.youtube.com/fcbayern',
                'instagram_url' => 'https://www.instagram.com/fcbayern/',
            ],
            [
                'id' => 4,
                'name' => 'ボルシア・ドルトムント',
                'short_name' => 'ドルトムント',
                'crest' => '4.png',
                'venue' => 'ジグナル・イドゥナ・パルク',
                'website_url' => 'https://www.bvb.de/',
                'twitter_url' => 'https://twitter.com/BlackYellow',
                'youtube_url' => 'https://www.youtube.com/@BVB',
                'instagram_url' => 'https://www.instagram.com/bvb09/',
            ],
            [
                'id' => 281,
                'name' => 'ウニオン・ベルリン',
                'short_name' => null,
                'crest' => '281.png',
                'venue' => 'アン・デア・アルテン・フェルステライ',
                'website_url' => 'https://www.fc-union-berlin.de/en/',
                'twitter_url' => 'https://twitter.com/fcunion',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/1.fcunion/',
            ],
            [
                'id' => 17,
                'name' => 'フライブルク',
                'short_name' => null,
                'crest' => '17.png',
                'venue' => 'オイローパ＝パルク・シュタディオン',
                'website_url' => 'https://www.scfreiburg.com/',
                'twitter_url' => 'https://twitter.com/scfreiburg',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/scfreiburg/',
            ],
            [
                'id' => 19,
                'name' => 'フランクフルト',
                'short_name' => null,
                'crest' => '19.png',
                'venue' => 'ヴァルトシュタディオン',
                'website_url' => 'https://www.eintracht.de/',
                'twitter_url' => 'https://twitter.com/eintracht',
                'youtube_url' => 'https://www.youtube.com/EintrachtMedia/',
                'instagram_url' => 'https://www.instagram.com/eintrachtfrankfurt/',
            ],
            [
                'id' => 3,
                'name' => 'バイエル・レバークーゼン',
                'short_name' => 'レバークーゼン',
                'crest' => '3.png',
                'venue' => 'バイ・アレーナ',
                'website_url' => 'https://www.bayer04.de/en-us',
                'twitter_url' => 'https://twitter.com/bayer04_en',
                'youtube_url' => 'https://www.youtube.com/bayerleverkusen',
                'instagram_url' => 'https://www.instagram.com/bayer04fussball/',
            ],
            [
                'id' => 151,
                'name' => 'FSVマインツ05',
                'short_name' => 'マインツ',
                'crest' => '151.png',
                'venue' => 'オペル・アレーナ',
                'website_url' => 'https://www.mainz05.de/',
                'twitter_url' => 'https://twitter.com/mainz05_jp',
                'youtube_url' => 'https://www.youtube.com/1FSVMainz05',
                'instagram_url' => 'https://www.instagram.com/1fsvmainz05/',
            ],
            [
                'id' => 11,
                'name' => 'ヴォルフスブルク',
                'short_name' => null,
                'crest' => '11.png',
                'venue' => 'フォルクスワーゲン・アレーナ',
                'website_url' => 'https://www.vfl-wolfsburg.de/',
                'twitter_url' => 'https://twitter.com/VfLWolfsburg_EN',
                'youtube_url' => 'https://www.youtube.com/@VfLWolfsburg',
                'instagram_url' => 'https://www.instagram.com/vfl.wolfsburg/',
            ],
            [
                'id' => 18,
                'name' => 'ボルシア・メンヘングラードバッハ',
                'short_name' => 'ボルシアMG',
                'crest' => '18.png',
                'venue' => 'シュタディオン・イム・ボルシア・パルク',
                'website_url' => 'https://www.borussia.de/de/',
                'twitter_url' => 'https://twitter.com/borussia_en',
                'youtube_url' => 'https://www.youtube.com/borussiatv',
                'instagram_url' => 'https://www.instagram.com/borussia/',
            ],
            [
                'id' => 12,
                'name' => 'ヴェルダー',
                'short_name' => null,
                'crest' => '12.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 16,
                'name' => 'アウクスブルク',
                'short_name' => null,
                'crest' => '16.png',
                'venue' => 'インパルス・アレーナ',
                'website_url' => 'https://www.fcaugsburg.de/',
                'twitter_url' => 'https://twitter.com/FCA_jp',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/fcaugsburg1907/',
            ],
            [
                'id' => 1,
                'name' => 'ケルン',
                'short_name' => null,
                'crest' => '1.png',
                'venue' => 'ラインエネルギーシュタディオン',
                'website_url' => 'https://www.fc.de/start/',
                'twitter_url' => 'https://twitter.com/fckoeln_jp',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/fckoeln/',
            ],
            [
                'id' => 36,
                'name' => 'ボーフム',
                'short_name' => null,
                'crest' => '36.png',
                'venue' => 'ルールシュタディオン',
                'website_url' => 'https://www.vfl-bochum.de/de',
                'twitter_url' => 'https://twitter.com/VfLBochum1848EN',
                'youtube_url' => 'https://www.youtube.com/VfLBochum1848',
                'instagram_url' => 'https://www.instagram.com/vflbochum1848.official/',
            ],
            [
                'id' => 2,
                'name' => 'TSG1899ホッフェンハイム',
                'short_name' => 'ホッフェンハイム',
                'crest' => '2.png',
                'venue' => 'ライン・ネッカー・アレーナ',
                'website_url' => 'https://www.tsg-hoffenheim.de/',
                'twitter_url' => 'https://twitter.com/tsghoffenheim',
                'youtube_url' => 'https://www.youtube.com/TSG1899Hoffenheim',
                'instagram_url' => 'https://www.instagram.com/tsghoffenheim/',
            ],
            [
                'id' => 9,
                'name' => 'ヘルタ',
                'short_name' => null,
                'crest' => '9.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 6,
                'name' => 'シャルケ04',
                'short_name' => 'シャルケ',
                'crest' => '6.png',
                'venue' => 'フェルティンス・アレーナ',
                'website_url' => 'https://schalke04.de/en/',
                'twitter_url' => 'https://twitter.com/s04',
                'youtube_url' => 'https://www.youtube.com/S04',
                'instagram_url' => 'https://www.instagram.com/s04/',
            ],
            [
                'id' => 10,
                'name' => 'シュトゥットガルト',
                'short_name' => null,
                'crest' => '10.png',
                'venue' => 'MHPアレーナ',
                'website_url' => 'https://www.vfb.de/',
                'twitter_url' => 'https://twitter.com/VfB_int',
                'youtube_url' => 'https://www.youtube.com/vfb',
                'instagram_url' => 'https://www.instagram.com/vfb/',
            ],
            [
                'id' => 55,
                'name' => 'SVダルムシュタット98',
                'short_name' => 'ダルムシュタット',
                'crest' => '98.png',
                'venue' => 'メルク・シュタディオン・アム・ベーレンファルター',
                'website_url' => 'https://www.sv98.de/',
                'twitter_url' => 'https://twitter.com/sv98',
                'youtube_url' => 'https://www.youtube.com/@SVDarmstadt1898',
                'instagram_url' => 'https://www.instagram.com/svdarmstadt1898/',
            ],
            [
                'id' => 44,
                'name' => 'ハイデンハイム',
                'short_name' => null,
                'crest' => '44.png',
                'venue' => 'フォイト・アレーナ',
                'website_url' => 'https://www.fc-heidenheim.de/',
                'twitter_url' => 'https://twitter.com/FCH1846',
                'youtube_url' => 'https://www.youtube.com/FCHpodcast',
                'instagram_url' => 'https://www.instagram.com/fch_1846/',
            ],
            [
                'id' => 721,
                'name' => 'RBライプツィヒ',
                'short_name' => null,
                'crest' => '721.png',
                'venue' => 'レッドブル・アレナ',
                'website_url' => 'https://rbleipzig.com/en/',
                'twitter_url' => 'https://twitter.com/RBLeipzig_EN',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/rbleipzig/',
            ],
            // セリエA
            [
                'id' => 113,
                'name' => 'ナポリ',
                'short_name' => null,
                'crest' => '113.png',
                'venue' => 'スタディオ・ディエゴ・アルマンド・マラドーナ',
                'website_url' => 'https://sscnapoli.it/',
                'twitter_url' => 'https://twitter.com/sscnapoli/',
                'youtube_url' => 'https://www.youtube.com/SSCNapoli',
                'instagram_url' => 'https://www.instagram.com/officialsscnapoli/',
            ],
            [
                'id' => 110,
                'name' => 'ラツィオ',
                'short_name' => 'ラツィオ',
                'crest' => '110.png',
                'venue' => 'スタディオ・オリンピコ・ディ・ローマ',
                'website_url' => 'https://www.sslazio.it/',
                'twitter_url' => 'https://twitter.com/OfficialSSLazio',
                'youtube_url' => 'https://www.youtube.com/Officialsslazio',
                'instagram_url' => 'https://instagram.com/official_sslazio/',
            ],
            [
                'id' => 98,
                'name' => 'ACミラン',
                'short_name' => null,
                'crest' => '98.png',
                'venue' => 'スタディオ・ジュゼッペ・メアッツァ',
                'website_url' => 'https://www.acmilan.com/',
                'twitter_url' => 'https://twitter.com/acmilan',
                'youtube_url' => 'https://www.youtube.com/acmilan',
                'instagram_url' => 'https://www.instagram.com/acmilan/',
            ],
            [
                'id' => 108,
                'name' => 'インテル',
                'short_name' => null,
                'crest' => '108.png',
                'venue' => 'スタディオ・ジュゼッペ・メアッツァ',
                'website_url' => 'https://www.inter.it/it',
                'twitter_url' => 'https://twitter.com/Inter',
                'youtube_url' => 'https://www.youtube.com/user/INTER',
                'instagram_url' => 'https://www.instagram.com/inter/',
            ],
            [
                'id' => 100,
                'name' => 'ローマ',
                'short_name' => '',
                'crest' => '100.png',
                'venue' => 'スタディオ・オリンピコ・ディ・ローマ',
                'website_url' => 'https://www.asroma.com/',
                'twitter_url' => 'https://twitter.com/OfficialASRoma',
                'youtube_url' => 'https://www.youtube.com/asroma',
                'instagram_url' => 'https://www.instagram.com/officialasroma/',
            ],
            [
                'id' => 102,
                'name' => 'アタランタ',
                'short_name' => null,
                'crest' => '102.png',
                'venue' => 'スタディオ・アトレティ・アズーリ・ディターリア',
                'website_url' => 'https://www.atalanta.it/',
                'twitter_url' => 'http://twitter.com/Atalanta_BC',
                'youtube_url' => 'http://www.youtube.com/user/AtalantaBC1907',
                'instagram_url' => 'http://www.youtube.com/user/AtalantaBC1907',
            ],
            [
                'id' => 109,
                'name' => 'ユヴェントス',
                'short_name' => null,
                'crest' => '109.png',
                'venue' => 'アリアンツスタジアム',
                'website_url' => 'https://www.juventus.com/it/',
                'twitter_url' => 'https://twitter.com/juventusfc',
                'youtube_url' => 'https://www.youtube.com/juventus',
                'instagram_url' => 'https://instagram.com/juventus/',
            ],
            [
                'id' => 103,
                'name' => 'ボローニャ',
                'short_name' => null,
                'crest' => '103.png',
                'venue' => 'スタディオ・レナート・ダッラーラ',
                'website_url' => 'https://www.bolognafc.it/',
                'twitter_url' => 'https://twitter.com/BfcOfficialPage',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/officialbolognafc/',
            ],
            [
                'id' => 99,
                'name' => 'フィオレンティーナ',
                'short_name' => null,
                'crest' => '99.png',
                'venue' => 'スタディオ・アルテミオ・フランキ',
                'website_url' => 'https://www.acffiorentina.com/it',
                'twitter_url' => 'https://twitter.com/acffiorentina',
                'youtube_url' => 'https://www.youtube.com/acffiorentina',
                'instagram_url' => 'https://www.instagram.com/acffiorentina/',
            ],
            [
                'id' => 586,
                'name' => 'トリノ',
                'short_name' => null,
                'crest' => '586.png',
                'venue' => 'スタディオ・オリンピコ・グランデ・トリノ',
                'website_url' => 'https://www.torinofc.it/',
                'twitter_url' => 'https://twitter.com/TorinoFC_1906',
                'youtube_url' => 'https://www.youtube.com/TorinoFCOfficial',
                'instagram_url' => 'https://www.instagram.com/torinofc1906/',
            ],
            [
                'id' => 115,
                'name' => 'ウディネーゼ',
                'short_name' => null,
                'crest' => '115.png',
                'venue' => 'ダチア・アレーナ',
                'website_url' => 'https://www.udinese.it/',
                'twitter_url' => 'https://twitter.com/Udinese_1896',
                'youtube_url' => 'https://www.youtube.com/udinesechannel',
                'instagram_url' => 'https://www.instagram.com/udinesecalcio/',
            ],
            [
                'id' => 471,
                'name' => 'サッスオーロ',
                'short_name' => null,
                'crest' => '471.png',
                'venue' => 'マペイ・スタジアム＝チッタ・デル・トリコローレ',
                'website_url' => 'https://www.sassuolocalcio.it/',
                'twitter_url' => 'https://twitter.com/SassuoloUS',
                'youtube_url' => 'https://www.youtube.com/SassuoloChannel',
                'instagram_url' => 'https://www.instagram.com/sassuolocalcio/',
            ],
            [
                'id' => 589,
                'name' => 'レッチェ',
                'short_name' => null,
                'crest' => '589.png',
                'venue' => 'スタディオ・ヴィア・デル・マーレ',
                'website_url' => 'https://www.uslecce.it/',
                'twitter_url' => 'https://twitter.com/OfficialUSLecce',
                'youtube_url' => 'https://www.youtube.com/UCzc84VvVxLbeCQ2wYXV0VOg',
                'instagram_url' => 'https://www.instagram.com/uslecce/',
            ],
            [
                'id' => 488,
                'name' => 'スペツィア',
                'short_name' => null,
                'crest' => '488.png',
                'venue' => 'スタディオ・アルベルト・ピッコ',
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 450,
                'name' => 'エラス・ヴェローナ',
                'short_name' => null,
                'crest' => '450.png',
                'venue' => 'マルカントニオ・ベンテゴディ・スタジオ',
                'website_url' => 'https://www.hellasverona.it/',
                'twitter_url' => 'https://twitter.com/HellasVeronaFC',
                'youtube_url' => 'https://www.youtube.com/HellasVeronaFC1903',
                'instagram_url' => 'https://www.instagram.com/hellasveronafc/',
            ],
            [
                'id' => 584,
                'name' => 'サンプドリア',
                'short_name' => null,
                'crest' => '584.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 457,
                'name' => 'クレモネーゼ',
                'short_name' => null,
                'crest' => '457.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 5911,
                'name' => 'モンツァ',
                'short_name' => null,
                'crest' => '5911.png',
                'venue' => 'スタディオ・ブリアンテオ',
                'website_url' => 'https://www.acmonza.com/',
                'twitter_url' => 'https://twitter.com/ACMonza',
                'youtube_url' => 'https://www.youtube.com/@acmonzaofficial',
                'instagram_url' => 'https://www.instagram.com/acmonza/',
            ],
            [
                'id' => 445,
                'name' => 'エンポリ',
                'short_name' => null,
                'crest' => '445.png',
                'venue' => 'カルロ・カステッラーニ・スタジオ',
                'website_url' => 'https://empolifc.com/',
                'twitter_url' => 'https://twitter.com/EmpoliCalcio',
                'youtube_url' => 'https://www.youtube.com/EmpoliFC1920',
                'instagram_url' => 'https://www.instagram.com/empoli_fc_official/',
            ],
            [
                'id' => 455,
                'name' => 'サレルニターナ',
                'short_name' => null,
                'crest' => '455.png',
                'venue' => 'スタディオ・アレキ',
                'website_url' => 'https://www.ussalernitana1919.it/',
                'twitter_url' => 'https://twitter.com/OfficialUSS1919',
                'youtube_url' => 'https://www.youtube.com/@SalernitanaOfficial',
                'instagram_url' => 'https://www.instagram.com/ussalernitana1919official/',
            ],
            [
                'id' => 104,
                'name' => 'カリアリ',
                'short_name' => null,
                'crest' => '104.png',
                'venue' => 'サルデーニャ・アレーナ',
                'website_url' => 'https://www.cagliaricalcio.com/',
                'twitter_url' => 'https://twitter.com/cagliaricalcio',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/cagliaricalcio',
            ],
            [
                'id' => 470,
                'name' => 'フロジノーネ',
                'short_name' => null,
                'crest' => null,
                'venue' => 'スタディオ・ベニート・スティルペ',
                'website_url' => 'https://www.frosinonecalcio.com/',
                'twitter_url' => 'https://twitter.com/frosinone1928',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/frosinonecalcio/',
            ],
            [
                'id' => 107,
                'name' => 'ジェノア',
                'short_name' => null,
                'crest' => '107.png',
                'venue' => 'スタディオ・ルイジ・フェッラーリス',
                'website_url' => 'https://genoacfc.it/',
                'twitter_url' => 'https://twitter.com/GenoaCFC',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/genoacfc/',
            ],
            // リーグアン
            [
                'id' => 524,
                'name' => 'パリ・サンジェルマン',
                'short_name' => 'パリSG',
                'crest' => '524.png',
                'venue' => 'パルク・デ・プランス',
                'website_url' => 'https://www.psg.fr/',
                'twitter_url' => 'https://twitter.com/PSG_inside',
                'youtube_url' => 'https://www.youtube.com/PSG',
                'instagram_url' => 'https://www.instagram.com/psg/',
            ],
            [
                'id' => 546,
                'name' => 'RCランス',
                'short_name' => null,
                'crest' => '546.png',
                'venue' => 'スタッド・フェリックス・ボラール',
                'website_url' => 'https://www.rclens.fr/fr',
                'twitter_url' => 'http://twitter.com/rclens',
                'youtube_url' => 'https://www.youtube.com/rclens',
                'instagram_url' => 'http://www.instagram.com/rclens',
            ],
            [
                'id' => 516,
                'name' => 'オリンピック・マルセイユ',
                'short_name' => 'マルセイユ',
                'crest' => '516.png',
                'venue' => 'スタッド・ヴェロドローム',
                'website_url' => 'https://www.om.fr/fr',
                'twitter_url' => 'https://twitter.com/OM_Officiel',
                'youtube_url' => 'https://www.youtube.com/OM',
                'instagram_url' => 'https://www.instagram.com/olympiquedemarseille/',
            ],
            [
                'id' => 548,
                'name' => 'ASモナコ',
                'short_name' => null,
                'crest' => '548.png',
                'venue' => 'スタッド・ルイ・ドゥ',
                'website_url' => 'https://www.asmonaco.com/',
                'twitter_url' => 'https://www.twitter.com/as_monaco',
                'youtube_url' => 'https://www.youtube.com/ASMONACO',
                'instagram_url' => 'https://www.instagram.com/asmonaco/',
            ],
            [
                'id' => 521,
                'name' => 'リール',
                'short_name' => null,
                'crest' => '521.png',
                'venue' => 'スタッド・ピエール＝モーロワ',
                'website_url' => 'https://www.losc.fr/',
                'twitter_url' => 'https://twitter.com/losclive',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/losclive/',
            ],
            [
                'id' => 529,
                'name' => 'スタッド・レンヌ',
                'short_name' => 'レンヌ',
                'crest' => '529.png',
                'venue' => 'ロアゾン・パルク',
                'website_url' => 'https://www.staderennais.com/',
                'twitter_url' => 'https://twitter.com/staderennais',
                'youtube_url' => null,
                'instagram_url' => 'https://instagram.com/staderennaisfc/',
            ],
            [
                'id' => 547,
                'name' => 'スタッド・ランス',
                'short_name' => 'ランス',
                'crest' => '547.png',
                'venue' => 'スタッド・オーギュスト＝ドローヌ',
                'website_url' => 'https://www.stade-de-reims.com/',
                'twitter_url' => 'https://twitter.com/StadedeReims',
                'youtube_url' => 'https://www.youtube.com/StadedeReimsOfficiel',
                'instagram_url' => 'https://instagram.com/stadedereims',
            ],
            [
                'id' => 522,
                'name' => 'ニース',
                'short_name' => null,
                'crest' => '522.png',
                'venue' => 'アリアンツ・リヴィエラ',
                'website_url' => 'https://www.ogcnice.com/fr/',
                'twitter_url' => 'https://twitter.com/ogcnice',
                'youtube_url' => 'https://www.youtube.com/ogcnice',
                'instagram_url' => 'https://www.instagram.com/ogcnice/',
            ],
            [
                'id' => 523,
                'name' => 'オリンピック・リヨン',
                'short_name' => 'リヨン',
                'crest' => '523.png',
                'venue' => 'パルク・オリンピック・リヨン',
                'website_url' => 'https://www.ol.fr/',
                'twitter_url' => 'https://twitter.com/ol',
                'youtube_url' => 'https://www.youtube.com/@OlympiqueLyonnais/',
                'instagram_url' => 'https://www.instagram.com/ol/',
            ],
            [
                'id' => 525,
                'name' => 'ロリアン',
                'short_name' => null,
                'crest' => '525.png',
                'venue' => 'ムトワール・スタジアム',
                'website_url' => 'https://www.fclorient.bzh/',
                'twitter_url' => 'https://twitter.com/FCLorient',
                'youtube_url' => 'https://www.youtube.com/@FCLorientOfficiel/',
                'instagram_url' => 'https://www.instagram.com/fclorient/',
            ],
            [
                'id' => 518,
                'name' => 'モンペリエ',
                'short_name' => null,
                'crest' => '518.png',
                'venue' => 'スタッド・ドゥ・ラ・モッソン',
                'website_url' => 'https://www.mhscfoot.com/',
                'twitter_url' => 'https://twitter.com/MontpellierHSC',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/mhscofficiel/',
            ],
            [
                'id' => 541,
                'name' => 'クレルモン',
                'short_name' => null,
                'crest' => '541.png',
                'venue' => 'スタッド・ガブリエル＝モンピエ',
                'website_url' => 'https://www.clermontfoot.com/',
                'twitter_url' => 'https://www.twitter.com/clermontfoot',
                'youtube_url' => null,
                'instagram_url' => 'https://www.instagram.com/clermontfoot/',
            ],
            [
                'id' => 511,
                'name' => 'トゥールーズ',
                'short_name' => null,
                'crest' => '511.png',
                'venue' => 'スタジアム・ド・トゥールーズ',
                'website_url' => 'https://www.toulousefc.com/fr',
                'twitter_url' => 'https://twitter.com/ToulouseFC',
                'youtube_url' => 'https://www.youtube.com/toulousefootballclub',
                'instagram_url' => 'https://www.instagram.com/toulousefc/',
            ],
            [
                'id' => 543,
                'name' => 'ナント',
                'short_name' => null,
                'crest' => '543.png',
                'venue' => 'スタッド・ドゥ・ラ・ボージョワール',
                'website_url' => 'https://www.fcnantes.com/',
                'twitter_url' => 'https://twitter.com/fcnantes',
                'youtube_url' => 'https://www.youtube.com/@FCNantes/',
                'instagram_url' => 'https://www.instagram.com/fcnantes/',
            ],
            [
                'id' => 512,
                'name' => 'スタッド・ブレスト29',
                'short_name' => 'ブレスト',
                'crest' => '512.png',
                'venue' => 'スタッド・フランシス＝ル・ブレ',
                'website_url' => 'https://www.sb29.bzh/',
                'twitter_url' => 'https://twitter.com/SB29',
                'youtube_url' => 'https://www.youtube.com/@SB29officiel/',
                'instagram_url' => 'https://www.instagram.com/stadebrestois29/',
            ],
            [
                'id' => 576,
                'name' => 'ストラスブール',
                'short_name' => null,
                'crest' => '576.png',
                'venue' => 'スタッド・ドゥ・ラ・メノ',
                'website_url' => 'https://www.rcstrasbourgalsace.fr/',
                'twitter_url' => 'https://twitter.com/RCSA',
                'youtube_url' => 'https://www.youtube.com/rcsaofficiel',
                'instagram_url' => 'https://www.instagram.com/rcsa/',
            ],
            [
                'id' => 519,
                'name' => 'オセール',
                'short_name' => null,
                'crest' => '519.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 531,
                'name' => 'トロワ',
                'short_name' => null,
                'crest' => '531.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 510,
                'name' => 'アジャクシオ',
                'short_name' => null,
                'crest' => '510.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 532,
                'name' => 'アンジェ',
                'short_name' => null,
                'crest' => '532.png',
                'venue' => null,
                'website_url' => null,
                'twitter_url' => null,
                'youtube_url' => null,
                'instagram_url' => null,
            ],
            [
                'id' => 533,
                'name' => 'ル・アーブル',
                'short_name' => null,
                'crest' => '533.png',
                'venue' => 'スタッド・オセアン',
                'website_url' => 'http://www.hac-foot.com/',
                'twitter_url' => 'https://twitter.com/HAC_Foot',
                'youtube_url' => '',
                'instagram_url' => 'https://www.instagram.com/hac_foot/',
            ],
            [
                'id' => 545,
                'name' => 'メス',
                'short_name' => null,
                'crest' => '545.png',
                'venue' => 'スタッド・サン＝サンフォリアン',
                'website_url' => 'https://www.fcmetz.com/',
                'twitter_url' => 'https://twitter.com/FCMetz',
                'youtube_url' => null,
                'instagram_url' => 'https://instagram.com/fcmetz/',
            ],

        ]);
    }
}
