<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamSeeder extends Seeder
{
    public function run()
    {
        DB::table('teams')->insert([
            [
                'id' => 57,
                'name' => 'アーセナル',
                'crest' => '57.png',
                'venue' => 'エミレーツスタジアム',
                'website' => 'https://www.arsenal.com/',
                'twitter' => 'https://twitter.com/arsenal_japan/',
                'youtube' => 'https://www.youtube.com/arsenal/',
                'instagram' => 'http://instagram.com/arsenal/',
            ],
            [
                'id' => 58,
                'name' => 'アストン・ビラ',
                'crest' => '58.png',
                'venue' => '',
                'website' => 'http://www.avfc.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 61,
                'name' => 'チェルシー',
                'crest' => '61.png',
                'venue' => 'スタンフォード・ブリッジ',
                'website' => 'http://www.chelseafc.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 62,
                'name' => 'エヴァートン',
                'crest' => '62.png',
                'venue' => '',
                'website' => 'http://www.evertonfc.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 63,
                'name' => 'フラム',
                'crest' => '63.png',
                'venue' => '',
                'website' => 'http://www.fulhamfc.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 64,
                'name' => 'リヴァプール',
                'crest' => '64.png',
                'venue' => '',
                'website' => 'http://www.liverpoolfc.tv',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 65,
                'name' => 'マンチェスターシティ',
                'crest' => '65.png',
                'venue' => 'スタンフォード・ブリッジ',
                'website' => 'https://www.mancity.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 66,
                'name' => 'マンチェスターユナイテッド',
                'crest' => '66.png',
                'venue' => 'オールド・トラッフォード',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 397,
                'name' => 'ブライトン',
                'crest' => '397.webp',
                'venue' => 'ファルマー・スタジアム',
                'website' => 'http://www.seagulls.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 67,
                'name' => 'ニューカッスル',
                'crest' => '67.png',
                'venue' => 'セント・ジェームズ・パーク',
                'website' => 'http://www.nufc.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 73,
                'name' => 'トッテナム',
                'crest' => '73.webp',
                'venue' => 'トッテナム・ホットスパー・スタジアム',
                'website' => 'http://www.tottenhamhotspur.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 76,
                'name' => 'ウルブス',
                'crest' => '76.webp',
                'venue' => '',
                'website' => 'http://www.wolves.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 338,
                'name' => 'レスター',
                'crest' => '338.png',
                'venue' => '',
                'website' => 'http://www.lcfc.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 340,
                'name' => 'サウサンプトン',
                'crest' => '340.png',
                'venue' => '',
                'website' => 'http://www.saintsfc.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 341,
                'name' => 'リーズU',
                'crest' => '341.png',
                'venue' => '',
                'website' => 'http://www.leedsunited.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 351,
                'name' => 'ノッティンガム',
                'crest' => '351.png',
                'venue' => '',
                'website' => 'http://www.nottinghamforest.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 354,
                'name' => 'クリスタル・パレス',
                'crest' => '354.png',
                'venue' => '',
                'website' => 'http://www.cpfc.co.uk',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 402,
                'name' => 'ブレントフォード',
                'crest' => '402.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 563,
                'name' => 'ウエストハム',
                'crest' => '563.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 1044,
                'name' => 'ボーンマス',
                'crest' => '1044.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 81,
                'name' => 'バルセロナ',
                'crest' => '81.png',
                'venue' => 'カンプ・ノウ',
                'website' => 'http://www.fcbarcelona.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 86,
                'name' => 'レアルマドリード',
                'crest' => '86.png',
                'venue' => 'エスタディオ・サンティアゴ・ベルナベウ',
                'website' => 'http://www.realmadrid.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 78,
                'name' => 'アトレティコ・マドリード',
                'crest' => '78.png',
                'venue' => 'ワンダ・メトロポリターノ',
                'website' => 'http://www.clubatleticodemadrid.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 92,
                'name' => 'レアル・ソシエダ',
                'crest' => '92.png',
                'venue' => 'エスタディオ・アノエタ',
                'website' => 'http://www.realsociedad.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 90,
                'name' => 'ベティス',
                'crest' => '90.png',
                'venue' => 'エスタディオ・ベニート・ヴィジャマリン',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 94,
                'name' => 'ビジャレアル',
                'crest' => '94.png',
                'venue' => 'エスタディオ・デ・ラ・セラミカ',
                'website' => 'http://www.villarrealcf.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 77,
                'name' => 'アスレティック・ビルバオ',
                'crest' => '77.png',
                'venue' => 'サン・マメス',
                'website' => 'http://www.athletic-club.eus',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 87,
                'name' => 'ラージョ・バジェカーノ',
                'crest' => '87.png',
                'venue' => 'カンポ・デ・フトボル・デ・バジェカス',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 79,
                'name' => 'オサスナ',
                'crest' => '79.png',
                'venue' => 'エスタディオ・エル・サダー',
                'website' => 'http://www.osasuna.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 558,
                'name' => 'セルタ',
                'crest' => '558.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 298,
                'name' => 'ジローナ',
                'crest' => '298.png',
                'venue' => '',
                'website' => 'http://www.gironafc.cat',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 89,
                'name' => 'マジョルカ',
                'crest' => '89.png',
                'venue' => 'エスタディ・デ・ソン・モイシュ',
                'website' => 'http://www.rcdmallorca.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 559,
                'name' => 'セビージャ',
                'crest' => '559.png',
                'venue' => 'エスタディオ・ラモン・サンチェス・ピスファン',
                'website' => 'http://www.sevillafc.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 82,
                'name' => 'ヘタフェ',
                'crest' => '82.png',
                'venue' => 'エスタディオ・コリセウム・アルフォンソ・ペレス',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 264,
                'name' => 'カディス',
                'crest' => '264.png',
                'venue' => 'エスタディオ・ラモン・デ・カッランツァ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 250,
                'name' => 'バジャドリード',
                'crest' => '250.png',
                'venue' => '',
                'website' => 'http://www.realvalladolid.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 95,
                'name' => 'バレンシア',
                'crest' => '95.png',
                'venue' => 'エスタディオ・デ・メスタージ',
                'website' => 'http://www.valenciacf.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 80,
                'name' => 'エスパニョール',
                'crest' => '80.png',
                'venue' => 'RCDEスタジアム',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 267,
                'name' => 'アルメリア',
                'crest' => '267.png',
                'venue' => '',
                'website' => 'http://www.udalmeriasad.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 285,
                'name' => 'エルチェ',
                'crest' => '285.png',
                'venue' => 'エスタディオ・マヌエル・マルティネス・ヴァレーロ',
                'website' => 'http://www.elchecf.es',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 5,
                'name' => 'バイエルン',
                'crest' => '5.png',
                'venue' => 'アリアンツ アレーナ',
                'website' => 'http://www.fcbayern.de',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 4,
                'name' => 'ドルトムント',
                'crest' => '4.png',
                'venue' => 'ジグナル・イドゥナ・パルク',
                'website' => 'http://www.bvb.de',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 281,
                'name' => 'ウニオン・ベルリン',
                'crest' => '281.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 17,
                'name' => 'フライブルク',
                'crest' => '17.png',
                'venue' => '',
                'website' => 'http://www.scfreiburg.com',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 19,
                'name' => 'フランクフルト',
                'crest' => '19.png',
                'venue' => 'ヴァルトシュタディオン',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 3,
                'name' => 'レバークーゼン',
                'crest' => '3.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 151,
                'name' => 'マインツ',
                'crest' => '151.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 11,
                'name' => 'ヴォルフスブルク',
                'crest' => '11.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 18,
                'name' => 'ボルシアMG',
                'crest' => '18.png',
                'venue' => 'シュタディオン・イム・ボルシア・パルク',
                'website' => 'http://www.borussia.de',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 12,
                'name' => 'ヴェルダー',
                'crest' => '12.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 16,
                'name' => 'アウクスブルク',
                'crest' => '16.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 1,
                'name' => 'ケルン',
                'crest' => '1.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 36,
                'name' => 'ボーフム',
                'crest' => '36.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 2,
                'name' => 'ホッフェンハイム',
                'crest' => '2.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 9,
                'name' => 'ヘルタ',
                'crest' => '9.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 6,
                'name' => 'シャルケ',
                'crest' => '6.png',
                'venue' => 'フェルティンス・アレーナ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 10,
                'name' => 'シュトゥットガルト',
                'crest' => '10.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 113,
                'name' => 'ナポリ',
                'crest' => '113.png',
                'venue' => 'スタディオ・ディエゴ・アルマンド・マラドーナ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 110,
                'name' => 'ラツィオ',
                'crest' => '110.webp',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 98,
                'name' => 'ACミラン',
                'crest' => '98.png',
                'venue' => 'スタディオ・ジュゼッペ・メアッツァ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 108,
                'name' => 'インテル',
                'crest' => '108.png',
                'venue' => 'スタディオ・ジュゼッペ・メアッツァ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 100,
                'name' => 'ローマ',
                'crest' => '100.webp',
                'venue' => 'スタディオ・オリンピコ・ディ・ローマ',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 102,
                'name' => 'アタランタ',
                'crest' => '102.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 109,
                'name' => 'ユヴェントス',
                'crest' => '109.png',
                'venue' => 'アリアンツスタジアム',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 103,
                'name' => 'ボローニャ',
                'crest' => '103.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 99,
                'name' => 'フィオレンティーナ',
                'crest' => '99.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 586,
                'name' => 'トリノ',
                'crest' => '586.webp',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 115,
                'name' => 'ウディネーゼ',
                'crest' => '115.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 471,
                'name' => 'サッスオーロ',
                'crest' => '471.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 589,
                'name' => 'レッチェ',
                'crest' => '589.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 488,
                'name' => 'スペツィア',
                'crest' => '488.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 450,
                'name' => 'エラス・ヴェローナ',
                'crest' => '450.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 584,
                'name' => 'サンプドリア',
                'crest' => '584.webp',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 457,
                'name' => 'クレモネーゼ',
                'crest' => '457.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 5911,
                'name' => 'モンツァ',
                'crest' => '5911.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 445,
                'name' => 'エンポリ',
                'crest' => '445.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 455,
                'name' => 'サレルニターナ',
                'crest' => '455.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 524,
                'name' => 'パリ・サンジェルマン',
                'crest' => '524.png',
                'venue' => 'パルク・デ・プランス',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 546,
                'name' => 'RCランス',
                'crest' => '546.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 516,
                'name' => 'マルセイユ',
                'crest' => '516.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 548,
                'name' => 'モナコ',
                'crest' => '548.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 521,
                'name' => 'リール',
                'crest' => '521.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 529,
                'name' => 'レンヌ',
                'crest' => '529.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 547,
                'name' => 'スタッド・ランス',
                'crest' => '547.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 522,
                'name' => 'ニース',
                'crest' => '522.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 523,
                'name' => 'リヨン',
                'crest' => '523.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 525,
                'name' => 'ロリアン',
                'crest' => '525.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 518,
                'name' => 'モンペリエ',
                'crest' => '518.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 541,
                'name' => 'クレルモン',
                'crest' => '541.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 511,
                'name' => 'トゥールーズ',
                'crest' => '511.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 543,
                'name' => 'ナント',
                'crest' => '543.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 512,
                'name' => 'ブレスト',
                'crest' => '512.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 576,
                'name' => 'ストラスブール',
                'crest' => '576.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 519,
                'name' => 'オセール',
                'crest' => '519.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 531,
                'name' => 'トロワ',
                'crest' => '531.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 510,
                'name' => 'アジャクシオ',
                'crest' => '510.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 532,
                'name' => 'アンジェ',
                'crest' => '532.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 5890,
                'name' => 'レッチェ',
                'crest' => '5890.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 721,
                'name' => 'RBライプツィヒ',
                'crest' => '721.webp',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 28,
                'name' => 'ウニオン・ベルリン',
                'crest' => '28.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
            [
                'id' => 15,
                'name' => 'マインツ',
                'crest' => '15.png',
                'venue' => '',
                'website' => '',
                'twitter' => '',
                'youtube' => '',
                'instagram' => '',
            ],
        ]);
    }
}
